set SOLUTION_DIR=%1
set PROJECT_DIR=%2
set PLATFORM_TARGET=%3
set CONFIGURATION=%4

set LIB_SOURCE=%PROJECT_DIR%\Lib\%PLATFORM_TARGET%\%CONFIGURATION%
set LIB_TARGET=%SOLUTION_DIR%\%PLATFORM_TARGET%\%CONFIGURATION%
 
xcopy /y "%LIB_SOURCE%\*.dll" "%LIBTARGET%\*.dll"