set SOLUTION_DIR=%1
set PROJECT_DIR=%2
set PLATFORM_TARGET=%3
set CONFIGURATION=%4

set LIBFBXSDK_SOURCE=%PROJECT_DIR%\Lib\%PLATFORM_TARGET%\%CONFIGURATION%\libfbxsdk.dll
set LIBFBXSDK_TARGET=%SOLUTION_DIR%\%PLATFORM_TARGET%\%CONFIGURATION%\libfbxsdk.dll
 
copy %LIBFBXSDK_SOURCE% %LIBFBXSDK_TARGET%