//-= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= 


#ifndef WINDOWS_HELPER_H_INCLUDE_GUARD
#define WINDOWS_HELPER_H_INCLUDE_GUARD


//-= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= 

#define WIN32_LEAN_AND_MEAN
#include <Windows.h>
#include <unordered_map>
#include <string>

//-= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= 



const std::string& wmtos( UINT uMsg )
{
      static std::unordered_map<UINT,std::string> s_map = []( void ) -> std::unordered_map<UINT,std::string>
      {
            std::unordered_map<UINT, std::string> map;
            map.emplace(WM_NULL , "WM_NULL"),
            map.emplace(WM_CREATE , "WM_CREATE"),
            map.emplace(WM_DESTROY , "WM_DESTROY"),
            map.emplace(WM_MOVE , "WM_MOVE"),
            map.emplace(WM_SIZE , "WM_SIZE"),
            map.emplace(WM_ACTIVATE , "WM_ACTIVATE"),
            map.emplace(WM_SETFOCUS , "WM_SETFOCUS"),
            map.emplace(WM_KILLFOCUS , "WM_KILLFOCUS"),
            map.emplace(WM_ENABLE , "WM_ENABLE"),
            map.emplace(WM_SETREDRAW , "WM_SETREDRAW"),
            map.emplace(WM_SETTEXT , "WM_SETTEXT"),
            map.emplace(WM_GETTEXT , "WM_GETTEXT"),
            map.emplace(WM_GETTEXTLENGTH , "WM_GETTEXTLENGTH"),
            map.emplace(WM_PAINT , "WM_PAINT"),
            map.emplace(WM_CLOSE , "WM_CLOSE"),
            map.emplace(WM_QUERYENDSESSION , "WM_QUERYENDSESSION"),
            map.emplace(WM_QUIT , "WM_QUIT"),
            map.emplace(WM_QUERYOPEN , "WM_QUERYOPEN"),
            map.emplace(WM_ERASEBKGND , "WM_ERASEBKGND"),
            map.emplace(WM_SYSCOLORCHANGE , "WM_SYSCOLORCHANGE"),
            map.emplace(WM_ENDSESSION , "WM_ENDSESSION"),
            map.emplace(WM_SHOWWINDOW , "WM_SHOWWINDOW"),
            map.emplace(WM_WININICHANGE , "WM_WININICHANGE"),
            map.emplace(WM_SETTINGCHANGE , "WM_SETTINGCHANGE"),
            map.emplace(WM_DEVMODECHANGE , "WM_DEVMODECHANGE"),
            map.emplace(WM_ACTIVATEAPP , "WM_ACTIVATEAPP"),
            map.emplace(WM_FONTCHANGE , "WM_FONTCHANGE"),
            map.emplace(WM_TIMECHANGE , "WM_TIMECHANGE"),
            map.emplace(WM_CANCELMODE , "WM_CANCELMODE"),
            map.emplace(WM_SETCURSOR , "WM_SETCURSOR"),
            map.emplace(WM_MOUSEACTIVATE , "WM_MOUSEACTIVATE"),
            map.emplace(WM_CHILDACTIVATE , "WM_CHILDACTIVATE"),
            map.emplace(WM_QUEUESYNC , "WM_QUEUESYNC"),
            map.emplace(WM_GETMINMAXINFO , "WM_GETMINMAXINFO"),
            map.emplace(WM_PAINTICON , "WM_PAINTICON"),
            map.emplace(WM_ICONERASEBKGND , "WM_ICONERASEBKGND"),
            map.emplace(WM_NEXTDLGCTL , "WM_NEXTDLGCTL"),
            map.emplace(WM_SPOOLERSTATUS , "WM_SPOOLERSTATUS"),
            map.emplace(WM_DRAWITEM , "WM_DRAWITEM"),
            map.emplace(WM_MEASUREITEM , "WM_MEASUREITEM"),
            map.emplace(WM_DELETEITEM , "WM_DELETEITEM"),
            map.emplace(WM_VKEYTOITEM , "WM_VKEYTOITEM"),
            map.emplace(WM_CHARTOITEM , "WM_CHARTOITEM"),
            map.emplace(WM_GETFONT , "WM_GETFONT"),
            map.emplace(WM_SETHOTKEY , "WM_SETHOTKEY"),
            map.emplace(WM_GETHOTKEY , "WM_GETHOTKEY"),
            map.emplace(WM_QUERYDRAGICON , "WM_QUERYDRAGICON"),
            map.emplace(WM_COMPAREITEM , "WM_COMPAREITEM"),
            map.emplace(WM_COMPACTING , "WM_COMPACTING"),
            map.emplace(WM_WINDOWPOSCHANGING , "WM_WINDOWPOSCHANGING"),
            map.emplace(WM_WINDOWPOSCHANGED , "WM_WINDOWPOSCHANGED"),
            map.emplace(WM_POWER , "WM_POWER"),
            map.emplace(WM_COPYDATA , "WM_COPYDATA"),
            map.emplace(WM_CANCELJOURNAL , "WM_CANCELJOURNAL"),
            map.emplace(WM_NOTIFY , "WM_NOTIFY"),
            map.emplace(WM_INPUTLANGCHANGEREQUEST , "WM_INPUTLANGCHANGEREQUEST"),
            map.emplace(WM_INPUTLANGCHANGE , "WM_INPUTLANGCHANGE"),
            map.emplace(WM_TCARD , "WM_TCARD"),
            map.emplace(WM_HELP , "WM_HELP"),
            map.emplace(WM_USERCHANGED , "WM_USERCHANGED"),
            map.emplace(WM_NOTIFYFORMAT , "WM_NOTIFYFORMAT"),
            map.emplace(WM_CONTEXTMENU , "WM_CONTEXTMENU"),
            map.emplace(WM_STYLECHANGING , "WM_STYLECHANGING"),
            map.emplace(WM_STYLECHANGED , "WM_STYLECHANGED"),
            map.emplace(WM_DISPLAYCHANGE , "WM_DISPLAYCHANGE"),
            map.emplace(WM_GETICON , "WM_GETICON"),
            map.emplace(WM_SETICON , "WM_SETICON"),
            map.emplace(WM_NCDESTROY , "WM_NCDESTROY"),
            map.emplace(WM_NCCALCSIZE , "WM_NCCALCSIZE"),
            map.emplace(WM_NCHITTEST , "WM_NCHITTEST"),
            map.emplace(WM_NCPAINT , "WM_NCPAINT"),
            map.emplace(WM_NCACTIVATE , "WM_NCACTIVATE"),
            map.emplace(WM_GETDLGCODE , "WM_GETDLGCODE"),
            map.emplace(WM_NCMOUSEMOVE , "WM_NCMOUSEMOVE"),
            map.emplace(WM_NCLBUTTONDOWN , "WM_NCLBUTTONDOWN"),
            map.emplace(WM_NCLBUTTONUP , "WM_NCLBUTTONUP"),
            map.emplace(WM_NCLBUTTONDBLCLK , "WM_NCLBUTTONDBLCLK"),
            map.emplace(WM_NCRBUTTONDOWN , "WM_NCRBUTTONDOWN"),
            map.emplace(WM_NCRBUTTONUP , "WM_NCRBUTTONUP"),
            map.emplace(WM_NCRBUTTONDBLCLK , "WM_NCRBUTTONDBLCLK"),
            map.emplace(WM_NCMBUTTONDOWN , "WM_NCMBUTTONDOWN"),
            map.emplace(WM_NCMBUTTONUP , "WM_NCMBUTTONUP"),
            map.emplace(WM_NCMBUTTONDBLCLK , "WM_NCMBUTTONDBLCLK"),
            map.emplace(WM_KEYDOWN , "WM_KEYDOWN"),
            map.emplace(WM_KEYUP , "WM_KEYUP"),
            map.emplace(WM_CHAR , "WM_CHAR"),
            map.emplace(WM_DEADCHAR , "WM_DEADCHAR"),
            map.emplace(WM_SYSKEYDOWN , "WM_SYSKEYDOWN"),
            map.emplace(WM_SYSKEYUP , "WM_SYSKEYUP"),
            map.emplace(WM_SYSCHAR , "WM_SYSCHAR"),
            map.emplace(WM_SYSDEADCHAR , "WM_SYSDEADCHAR"),
            map.emplace(WM_KEYLAST , "WM_KEYLAST"),
            map.emplace(WM_IME_ENDCOMPOSITION , "WM_IME_ENDCOMPOSITION"),
            map.emplace(WM_IME_COMPOSITION , "WM_IME_COMPOSITION"),
            map.emplace(WM_IME_KEYLAST , "WM_IME_KEYLAST"),
            map.emplace(WM_COMMAND , "WM_COMMAND"),
            map.emplace(WM_SYSCOMMAND , "WM_SYSCOMMAND"),
            map.emplace(WM_TIMER , "WM_TIMER"),
            map.emplace(WM_HSCROLL , "WM_HSCROLL"),
            map.emplace(WM_VSCROLL , "WM_VSCROLL"),
            map.emplace(WM_INITMENU , "WM_INITMENU"),
            map.emplace(WM_INITMENUPOPUP , "WM_INITMENUPOPUP"),
            map.emplace(WM_MENUSELECT , "WM_MENUSELECT"),
            map.emplace(WM_MENUCHAR , "WM_MENUCHAR"),
            map.emplace(WM_ENTERIDLE , "WM_ENTERIDLE"),
            map.emplace(WM_CTLCOLOREDIT , "WM_CTLCOLOREDIT"),
            map.emplace(WM_CTLCOLORLISTBOX , "WM_CTLCOLORLISTBOX"),
            map.emplace(WM_CTLCOLORBTN , "WM_CTLCOLORBTN"),
            map.emplace(WM_CTLCOLORDLG , "WM_CTLCOLORDLG"),
            map.emplace(WM_CTLCOLORSCROLLBAR , "WM_CTLCOLORSCROLLBAR"),
            map.emplace(WM_CTLCOLORSTATIC , "WM_CTLCOLORSTATIC"),
            map.emplace(WM_MOUSEMOVE , "WM_MOUSEMOVE"),
            map.emplace(WM_LBUTTONDOWN , "WM_LBUTTONDOWN"),
            map.emplace(WM_LBUTTONUP , "WM_LBUTTONUP"),
            map.emplace(WM_LBUTTONDBLCLK , "WM_LBUTTONDBLCLK"),
            map.emplace(WM_RBUTTONDOWN , "WM_RBUTTONDOWN"),
            map.emplace(WM_RBUTTONUP , "WM_RBUTTONUP"),
            map.emplace(WM_RBUTTONDBLCLK , "WM_RBUTTONDBLCLK"),
            map.emplace(WM_MBUTTONDOWN , "WM_MBUTTONDOWN"),
            map.emplace(WM_MBUTTONUP , "WM_MBUTTONUP"),
            map.emplace(WM_MBUTTONDBLCLK , "WM_MBUTTONDBLCLK"),
            map.emplace(WM_MOUSEWHEEL , "WM_MOUSEWHEEL"),
            map.emplace(WM_MOUSEHWHEEL , "WM_MOUSEHWHEEL"),
            map.emplace(WM_ENTERMENULOOP , "WM_ENTERMENULOOP"),
            map.emplace(WM_EXITMENULOOP , "WM_EXITMENULOOP"),
            map.emplace(WM_NEXTMENU , "WM_NEXTMENU"),
            map.emplace(WM_SIZING , "WM_SIZING"),
            map.emplace(WM_CAPTURECHANGED , "WM_CAPTURECHANGED"),
            map.emplace(WM_MOVING , "WM_MOVING"),
            map.emplace(WM_POWERBROADCAST , "WM_POWERBROADCAST"),
            map.emplace(WM_DEVICECHANGE , "WM_DEVICECHANGE"),
            map.emplace(WM_MDIDESTROY , "WM_MDIDESTROY"),
            map.emplace(WM_MDIACTIVATE , "WM_MDIACTIVATE"),
            map.emplace(WM_MDIRESTORE , "WM_MDIRESTORE"),
            map.emplace(WM_MDINEXT , "WM_MDINEXT"),
            map.emplace(WM_MDIMAXIMIZE , "WM_MDIMAXIMIZE"),
            map.emplace(WM_MDITILE , "WM_MDITILE"),
            map.emplace(WM_MDICASCADE , "WM_MDICASCADE"),
            map.emplace(WM_MDIICONARRANGE , "WM_MDIICONARRANGE"),
            map.emplace(WM_MDIGETACTIVE , "WM_MDIGETACTIVE"),
            map.emplace(WM_MDISETMENU , "WM_MDISETMENU"),
            map.emplace(WM_ENTERSIZEMOVE , "WM_ENTERSIZEMOVE"),
            map.emplace(WM_EXITSIZEMOVE , "WM_EXITSIZEMOVE"),
            map.emplace(WM_DROPFILES , "WM_DROPFILES"),
            map.emplace(WM_MDIREFRESHMENU , "WM_MDIREFRESHMENU"),
            map.emplace(WM_IME_NOTIFY , "WM_IME_NOTIFY"),
            map.emplace(WM_IME_CONTROL , "WM_IME_CONTROL"),
            map.emplace(WM_IME_COMPOSITIONFULL , "WM_IME_COMPOSITIONFULL"),
            map.emplace(WM_IME_SELECT , "WM_IME_SELECT"),
            map.emplace(WM_IME_CHAR , "WM_IME_CHAR"),
            map.emplace(WM_IME_KEYDOWN , "WM_IME_KEYDOWN"),
            map.emplace(WM_IME_KEYUP , "WM_IME_KEYUP"),
            map.emplace(WM_NCMOUSELEAVE , "WM_NCMOUSELEAVE"),
            map.emplace(WM_MOUSELEAVE , "WM_MOUSELEAVE"),
            map.emplace(WM_COPY , "WM_COPY"),
            map.emplace(WM_PASTE , "WM_PASTE"),
            map.emplace(WM_CLEAR , "WM_CLEAR"),
            map.emplace(WM_UNDO , "WM_UNDO"),
            map.emplace(WM_RENDERALLFORMATS , "WM_RENDERALLFORMATS"),
            map.emplace(WM_DESTROYCLIPBOARD , "WM_DESTROYCLIPBOARD"),
            map.emplace(WM_DRAWCLIPBOARD , "WM_DRAWCLIPBOARD"),
            map.emplace(WM_PAINTCLIPBOARD , "WM_PAINTCLIPBOARD"),
            map.emplace(WM_VSCROLLCLIPBOARD , "WM_VSCROLLCLIPBOARD"),
            map.emplace(WM_SIZECLIPBOARD , "WM_SIZECLIPBOARD"),
            map.emplace(WM_ASKCBFORMATNAME , "WM_ASKCBFORMATNAME"),
            map.emplace(WM_CHANGECBCHAIN , "WM_CHANGECBCHAIN"),
            map.emplace(WM_HSCROLLCLIPBOARD , "WM_HSCROLLCLIPBOARD"),
            map.emplace(WM_QUERYNEWPALETTE , "WM_QUERYNEWPALETTE"),
            map.emplace(WM_PALETTEISCHANGING , "WM_PALETTEISCHANGING"),
            map.emplace(WM_PALETTECHANGED , "WM_PALETTECHANGED"),
            map.emplace(WM_PRINT , "WM_PRINT"),
            map.emplace(WM_PRINTCLIENT , "WM_PRINTCLIENT"),
            map.emplace(WM_HANDHELDLAST , "WM_HANDHELDLAST"),
            map.emplace(WM_PENWINFIRST , "WM_PENWINFIRST"),
            map.emplace(WM_PENWINLAST , "WM_PENWINLAST"),
            //map.emplace(WM_DDE_FIRST , "WM_DDE_FIRST"),
            //map.emplace(WM_DDE_INITIATE , "WM_DDE_INITIATE"),
            //map.emplace(WM_DDE_TERMINATE , "WM_DDE_TERMINATE"),
            //map.emplace(WM_DDE_ADVISE , "WM_DDE_ADVISE"),
            //map.emplace(WM_DDE_UNADVISE , "WM_DDE_UNADVISE"),
            //map.emplace(WM_DDE_ACK , "WM_DDE_ACK"),
            //map.emplace(WM_DDE_DATA , "WM_DDE_DATA"),
            //map.emplace(WM_DDE_REQUEST , "WM_DDE_REQUEST"),
            //map.emplace(WM_DDE_POKE , "WM_DDE_POKE"),
            //map.emplace(WM_DDE_EXECUTE , "WM_DDE_EXECUTE"),
            //map.emplace(WM_DDE_LAST , "WM_DDE_LAST"),
            map.emplace(WM_APP, "WM_AP");
            return map;
      }();
      return s_map[uMsg];
}

const std::wstring& wmtows( UINT uMsg )
{
      static std::unordered_map<UINT,std::wstring> s_map = []( void ) -> std::unordered_map<UINT,std::wstring>
      {
            std::unordered_map<UINT, std::wstring> map;
            map.emplace(WM_NULL , L"WM_NULL"),
            map.emplace(WM_CREATE , L"WM_CREATE"),
            map.emplace(WM_DESTROY , L"WM_DESTROY"),
            map.emplace(WM_MOVE , L"WM_MOVE"),
            map.emplace(WM_SIZE , L"WM_SIZE"),
            map.emplace(WM_ACTIVATE , L"WM_ACTIVATE"),
            map.emplace(WM_SETFOCUS , L"WM_SETFOCUS"),
            map.emplace(WM_KILLFOCUS , L"WM_KILLFOCUS"),
            map.emplace(WM_ENABLE , L"WM_ENABLE"),
            map.emplace(WM_SETREDRAW , L"WM_SETREDRAW"),
            map.emplace(WM_SETTEXT , L"WM_SETTEXT"),
            map.emplace(WM_GETTEXT , L"WM_GETTEXT"),
            map.emplace(WM_GETTEXTLENGTH , L"WM_GETTEXTLENGTH"),
            map.emplace(WM_PAINT , L"WM_PAINT"),
            map.emplace(WM_CLOSE , L"WM_CLOSE"),
            map.emplace(WM_QUERYENDSESSION , L"WM_QUERYENDSESSION"),
            map.emplace(WM_QUIT , L"WM_QUIT"),
            map.emplace(WM_QUERYOPEN , L"WM_QUERYOPEN"),
            map.emplace(WM_ERASEBKGND , L"WM_ERASEBKGND"),
            map.emplace(WM_SYSCOLORCHANGE , L"WM_SYSCOLORCHANGE"),
            map.emplace(WM_ENDSESSION , L"WM_ENDSESSION"),
            map.emplace(WM_SHOWWINDOW , L"WM_SHOWWINDOW"),
            map.emplace(WM_WININICHANGE , L"WM_WININICHANGE"),
            map.emplace(WM_SETTINGCHANGE , L"WM_SETTINGCHANGE"),
            map.emplace(WM_DEVMODECHANGE , L"WM_DEVMODECHANGE"),
            map.emplace(WM_ACTIVATEAPP , L"WM_ACTIVATEAPP"),
            map.emplace(WM_FONTCHANGE , L"WM_FONTCHANGE"),
            map.emplace(WM_TIMECHANGE , L"WM_TIMECHANGE"),
            map.emplace(WM_CANCELMODE , L"WM_CANCELMODE"),
            map.emplace(WM_SETCURSOR , L"WM_SETCURSOR"),
            map.emplace(WM_MOUSEACTIVATE , L"WM_MOUSEACTIVATE"),
            map.emplace(WM_CHILDACTIVATE , L"WM_CHILDACTIVATE"),
            map.emplace(WM_QUEUESYNC , L"WM_QUEUESYNC"),
            map.emplace(WM_GETMINMAXINFO , L"WM_GETMINMAXINFO"),
            map.emplace(WM_PAINTICON , L"WM_PAINTICON"),
            map.emplace(WM_ICONERASEBKGND , L"WM_ICONERASEBKGND"),
            map.emplace(WM_NEXTDLGCTL , L"WM_NEXTDLGCTL"),
            map.emplace(WM_SPOOLERSTATUS , L"WM_SPOOLERSTATUS"),
            map.emplace(WM_DRAWITEM , L"WM_DRAWITEM"),
            map.emplace(WM_MEASUREITEM , L"WM_MEASUREITEM"),
            map.emplace(WM_DELETEITEM , L"WM_DELETEITEM"),
            map.emplace(WM_VKEYTOITEM , L"WM_VKEYTOITEM"),
            map.emplace(WM_CHARTOITEM , L"WM_CHARTOITEM"),
            map.emplace(WM_GETFONT , L"WM_GETFONT"),
            map.emplace(WM_SETHOTKEY , L"WM_SETHOTKEY"),
            map.emplace(WM_GETHOTKEY , L"WM_GETHOTKEY"),
            map.emplace(WM_QUERYDRAGICON , L"WM_QUERYDRAGICON"),
            map.emplace(WM_COMPAREITEM , L"WM_COMPAREITEM"),
            map.emplace(WM_COMPACTING , L"WM_COMPACTING"),
            map.emplace(WM_WINDOWPOSCHANGING , L"WM_WINDOWPOSCHANGING"),
            map.emplace(WM_WINDOWPOSCHANGED , L"WM_WINDOWPOSCHANGED"),
            map.emplace(WM_POWER , L"WM_POWER"),
            map.emplace(WM_COPYDATA , L"WM_COPYDATA"),
            map.emplace(WM_CANCELJOURNAL , L"WM_CANCELJOURNAL"),
            map.emplace(WM_NOTIFY , L"WM_NOTIFY"),
            map.emplace(WM_INPUTLANGCHANGEREQUEST , L"WM_INPUTLANGCHANGEREQUEST"),
            map.emplace(WM_INPUTLANGCHANGE , L"WM_INPUTLANGCHANGE"),
            map.emplace(WM_TCARD , L"WM_TCARD"),
            map.emplace(WM_HELP , L"WM_HELP"),
            map.emplace(WM_USERCHANGED , L"WM_USERCHANGED"),
            map.emplace(WM_NOTIFYFORMAT , L"WM_NOTIFYFORMAT"),
            map.emplace(WM_CONTEXTMENU , L"WM_CONTEXTMENU"),
            map.emplace(WM_STYLECHANGING , L"WM_STYLECHANGING"),
            map.emplace(WM_STYLECHANGED , L"WM_STYLECHANGED"),
            map.emplace(WM_DISPLAYCHANGE , L"WM_DISPLAYCHANGE"),
            map.emplace(WM_GETICON , L"WM_GETICON"),
            map.emplace(WM_SETICON , L"WM_SETICON"),
            map.emplace(WM_NCDESTROY , L"WM_NCDESTROY"),
            map.emplace(WM_NCCALCSIZE , L"WM_NCCALCSIZE"),
            map.emplace(WM_NCHITTEST , L"WM_NCHITTEST"),
            map.emplace(WM_NCPAINT , L"WM_NCPAINT"),
            map.emplace(WM_NCACTIVATE , L"WM_NCACTIVATE"),
            map.emplace(WM_GETDLGCODE , L"WM_GETDLGCODE"),
            map.emplace(WM_NCMOUSEMOVE , L"WM_NCMOUSEMOVE"),
            map.emplace(WM_NCLBUTTONDOWN , L"WM_NCLBUTTONDOWN"),
            map.emplace(WM_NCLBUTTONUP , L"WM_NCLBUTTONUP"),
            map.emplace(WM_NCLBUTTONDBLCLK , L"WM_NCLBUTTONDBLCLK"),
            map.emplace(WM_NCRBUTTONDOWN , L"WM_NCRBUTTONDOWN"),
            map.emplace(WM_NCRBUTTONUP , L"WM_NCRBUTTONUP"),
            map.emplace(WM_NCRBUTTONDBLCLK , L"WM_NCRBUTTONDBLCLK"),
            map.emplace(WM_NCMBUTTONDOWN , L"WM_NCMBUTTONDOWN"),
            map.emplace(WM_NCMBUTTONUP , L"WM_NCMBUTTONUP"),
            map.emplace(WM_NCMBUTTONDBLCLK , L"WM_NCMBUTTONDBLCLK"),
            map.emplace(WM_KEYDOWN , L"WM_KEYDOWN"),
            map.emplace(WM_KEYUP , L"WM_KEYUP"),
            map.emplace(WM_CHAR , L"WM_CHAR"),
            map.emplace(WM_DEADCHAR , L"WM_DEADCHAR"),
            map.emplace(WM_SYSKEYDOWN , L"WM_SYSKEYDOWN"),
            map.emplace(WM_SYSKEYUP , L"WM_SYSKEYUP"),
            map.emplace(WM_SYSCHAR , L"WM_SYSCHAR"),
            map.emplace(WM_SYSDEADCHAR , L"WM_SYSDEADCHAR"),
            map.emplace(WM_KEYLAST , L"WM_KEYLAST"),
            map.emplace(WM_IME_ENDCOMPOSITION , L"WM_IME_ENDCOMPOSITION"),
            map.emplace(WM_IME_COMPOSITION , L"WM_IME_COMPOSITION"),
            map.emplace(WM_IME_KEYLAST , L"WM_IME_KEYLAST"),
            map.emplace(WM_COMMAND , L"WM_COMMAND"),
            map.emplace(WM_SYSCOMMAND , L"WM_SYSCOMMAND"),
            map.emplace(WM_TIMER , L"WM_TIMER"),
            map.emplace(WM_HSCROLL , L"WM_HSCROLL"),
            map.emplace(WM_VSCROLL , L"WM_VSCROLL"),
            map.emplace(WM_INITMENU , L"WM_INITMENU"),
            map.emplace(WM_INITMENUPOPUP , L"WM_INITMENUPOPUP"),
            map.emplace(WM_MENUSELECT , L"WM_MENUSELECT"),
            map.emplace(WM_MENUCHAR , L"WM_MENUCHAR"),
            map.emplace(WM_ENTERIDLE , L"WM_ENTERIDLE"),
            map.emplace(WM_CTLCOLOREDIT , L"WM_CTLCOLOREDIT"),
            map.emplace(WM_CTLCOLORLISTBOX , L"WM_CTLCOLORLISTBOX"),
            map.emplace(WM_CTLCOLORBTN , L"WM_CTLCOLORBTN"),
            map.emplace(WM_CTLCOLORDLG , L"WM_CTLCOLORDLG"),
            map.emplace(WM_CTLCOLORSCROLLBAR , L"WM_CTLCOLORSCROLLBAR"),
            map.emplace(WM_CTLCOLORSTATIC , L"WM_CTLCOLORSTATIC"),
            map.emplace(WM_MOUSEMOVE , L"WM_MOUSEMOVE"),
            map.emplace(WM_LBUTTONDOWN , L"WM_LBUTTONDOWN"),
            map.emplace(WM_LBUTTONUP , L"WM_LBUTTONUP"),
            map.emplace(WM_LBUTTONDBLCLK , L"WM_LBUTTONDBLCLK"),
            map.emplace(WM_RBUTTONDOWN , L"WM_RBUTTONDOWN"),
            map.emplace(WM_RBUTTONUP , L"WM_RBUTTONUP"),
            map.emplace(WM_RBUTTONDBLCLK , L"WM_RBUTTONDBLCLK"),
            map.emplace(WM_MBUTTONDOWN , L"WM_MBUTTONDOWN"),
            map.emplace(WM_MBUTTONUP , L"WM_MBUTTONUP"),
            map.emplace(WM_MBUTTONDBLCLK , L"WM_MBUTTONDBLCLK"),
            map.emplace(WM_MOUSEWHEEL , L"WM_MOUSEWHEEL"),
            map.emplace(WM_MOUSEHWHEEL , L"WM_MOUSEHWHEEL"),
            map.emplace(WM_ENTERMENULOOP , L"WM_ENTERMENULOOP"),
            map.emplace(WM_EXITMENULOOP , L"WM_EXITMENULOOP"),
            map.emplace(WM_NEXTMENU , L"WM_NEXTMENU"),
            map.emplace(WM_SIZING , L"WM_SIZING"),
            map.emplace(WM_CAPTURECHANGED , L"WM_CAPTURECHANGED"),
            map.emplace(WM_MOVING , L"WM_MOVING"),
            map.emplace(WM_POWERBROADCAST , L"WM_POWERBROADCAST"),
            map.emplace(WM_DEVICECHANGE , L"WM_DEVICECHANGE"),
            map.emplace(WM_MDIDESTROY , L"WM_MDIDESTROY"),
            map.emplace(WM_MDIACTIVATE , L"WM_MDIACTIVATE"),
            map.emplace(WM_MDIRESTORE , L"WM_MDIRESTORE"),
            map.emplace(WM_MDINEXT , L"WM_MDINEXT"),
            map.emplace(WM_MDIMAXIMIZE , L"WM_MDIMAXIMIZE"),
            map.emplace(WM_MDITILE , L"WM_MDITILE"),
            map.emplace(WM_MDICASCADE , L"WM_MDICASCADE"),
            map.emplace(WM_MDIICONARRANGE , L"WM_MDIICONARRANGE"),
            map.emplace(WM_MDIGETACTIVE , L"WM_MDIGETACTIVE"),
            map.emplace(WM_MDISETMENU , L"WM_MDISETMENU"),
            map.emplace(WM_ENTERSIZEMOVE , L"WM_ENTERSIZEMOVE"),
            map.emplace(WM_EXITSIZEMOVE , L"WM_EXITSIZEMOVE"),
            map.emplace(WM_DROPFILES , L"WM_DROPFILES"),
            map.emplace(WM_MDIREFRESHMENU , L"WM_MDIREFRESHMENU"),
            map.emplace(WM_IME_NOTIFY , L"WM_IME_NOTIFY"),
            map.emplace(WM_IME_CONTROL , L"WM_IME_CONTROL"),
            map.emplace(WM_IME_COMPOSITIONFULL , L"WM_IME_COMPOSITIONFULL"),
            map.emplace(WM_IME_SELECT , L"WM_IME_SELECT"),
            map.emplace(WM_IME_CHAR , L"WM_IME_CHAR"),
            map.emplace(WM_IME_KEYDOWN , L"WM_IME_KEYDOWN"),
            map.emplace(WM_IME_KEYUP , L"WM_IME_KEYUP"),
            map.emplace(WM_NCMOUSELEAVE , L"WM_NCMOUSELEAVE"),
            map.emplace(WM_MOUSELEAVE , L"WM_MOUSELEAVE"),
            map.emplace(WM_COPY , L"WM_COPY"),
            map.emplace(WM_PASTE , L"WM_PASTE"),
            map.emplace(WM_CLEAR , L"WM_CLEAR"),
            map.emplace(WM_UNDO , L"WM_UNDO"),
            map.emplace(WM_RENDERALLFORMATS , L"WM_RENDERALLFORMATS"),
            map.emplace(WM_DESTROYCLIPBOARD , L"WM_DESTROYCLIPBOARD"),
            map.emplace(WM_DRAWCLIPBOARD , L"WM_DRAWCLIPBOARD"),
            map.emplace(WM_PAINTCLIPBOARD , L"WM_PAINTCLIPBOARD"),
            map.emplace(WM_VSCROLLCLIPBOARD , L"WM_VSCROLLCLIPBOARD"),
            map.emplace(WM_SIZECLIPBOARD , L"WM_SIZECLIPBOARD"),
            map.emplace(WM_ASKCBFORMATNAME , L"WM_ASKCBFORMATNAME"),
            map.emplace(WM_CHANGECBCHAIN , L"WM_CHANGECBCHAIN"),
            map.emplace(WM_HSCROLLCLIPBOARD , L"WM_HSCROLLCLIPBOARD"),
            map.emplace(WM_QUERYNEWPALETTE , L"WM_QUERYNEWPALETTE"),
            map.emplace(WM_PALETTEISCHANGING , L"WM_PALETTEISCHANGING"),
            map.emplace(WM_PALETTECHANGED , L"WM_PALETTECHANGED"),
            map.emplace(WM_PRINT , L"WM_PRINT"),
            map.emplace(WM_PRINTCLIENT , L"WM_PRINTCLIENT"),
            map.emplace(WM_HANDHELDLAST , L"WM_HANDHELDLAST"),
            map.emplace(WM_PENWINFIRST , L"WM_PENWINFIRST"),
            map.emplace(WM_PENWINLAST , L"WM_PENWINLAST"),
            //map.emplace(WM_DDE_FIRST , L"WM_DDE_FIRST"),
            //map.emplace(WM_DDE_INITIATE , L"WM_DDE_INITIATE"),
            //map.emplace(WM_DDE_TERMINATE , L"WM_DDE_TERMINATE"),
            //map.emplace(WM_DDE_ADVISE , L"WM_DDE_ADVISE"),
            //map.emplace(WM_DDE_UNADVISE , L"WM_DDE_UNADVISE"),
            //map.emplace(WM_DDE_ACK , L"WM_DDE_ACK"),
            //map.emplace(WM_DDE_DATA , L"WM_DDE_DATA"),
            //map.emplace(WM_DDE_REQUEST , L"WM_DDE_REQUEST"),
            //map.emplace(WM_DDE_POKE , L"WM_DDE_POKE"),
            //map.emplace(WM_DDE_EXECUTE , L"WM_DDE_EXECUTE"),
            //map.emplace(WM_DDE_LAST , L"WM_DDE_LAST"),
            map.emplace(WM_APP, L"WM_AP");
            return map;
      }();
      return s_map[uMsg];
}

//-= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= 


#endif //WINDOWS_HELPER_H_INCLUDE_GUARD


//-= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= -= 